config/routes.rb
Rails.application.routes.draw do
  resources :notes do
    get :today, on: :collection
  end

  devise_for :users

  root to: 'notes#today'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :title, :text, :user_id

  scope :today, -> { where(date: Date.today) }
  scope :between_dates, ->(from_date, to_date) { where("date >= ? AND date <= ?", from_date, to_date) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    search = params[:search]
    if search.present?
      @from_date = Date.new search["from_date(1i)"].to_i, search["from_date(2i)"].to_i, search["from_date(3i)"].to_i
      @to_date = Date.new search["to_date(1i)"].to_i, search["to_date(2i)"].to_i, search["to_date(3i)"].to_i
    else
      @from_date = Date.today
      @to_date = Date.today + 10.days
    end

    @notes = current_user.notes.between_dates(@from_date, @to_date)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def today
    @notes = current_user.notes.today
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :text, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Diary
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = link_to "Today notes", today_notes_path
    = link_to "All notes", notes_path
    = yield

app/views/notes/_form.html.slim
= simple_form_for(@note) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :text
    = f.input :date
  .form-actions
    = f.button :submit

app/views/notes/_notes_list.html.slim
- @notes.each do |note|
  tr
    td
      = note.title
    td
      = note.text
    td
      = note.date
    td
      = link_to 'Show', note
    td
      = link_to 'Edit', edit_note_path(note)
    td
      = link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }

app/views/notes/_search_form.html.slim
= simple_form_for :search, method: :get, remote: true do |s|
  = s.input :from_date, as: :date, default: @from_date
  = s.input :to_date, as: :date, default: @to_date
  = s.submit value: 'Search'

app/views/notes/edit.html.slim
h1
  | Editing Note
= render 'form'
= link_to 'Show', @note
|  | 
= link_to 'Back', notes_path

app/views/notes/index.html.slim
p#notice
  = notice
h1
  | Listing Notes
- if params[:action] == 'index'
  = render "search_form"
table
  thead
    tr
      th
        | Title
      th
        | Text
      th
        | Date
      th[colspan="3"]
  tbody = render "notes_list"
br
= link_to 'New Note', new_note_path

app/views/notes/index.js.erb
$('tbody').html('<%=j render "notes_list" %>');

app/views/notes/new.html.slim
h1
  | New Note
= render 'form'
= link_to 'Back', notes_path

app/views/notes/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @note.title
p
  strong
    | Text:
  = @note.text
p
  strong
    | Date:
  = @note.date
= link_to 'Edit', edit_note_path(@note)
|  | 
= link_to 'Back', notes_path